### ISSUE TITLE
Use API if ID of an item is not known

### ISSUE THREAD

**Issue by Banik1103** [Accutrix/Rolimons#1]
Hello there!

I'm trying to use create item objects, but I don't have the ID's of the items and was hoping to get the items' IDs  by using your API. Is there a way to create item objects without an item's ID?

**Comment by optimisticside** [comment]
You cannot create an item without the item's ID. I don't think there is any way to do this (Roblox doesn't provide any APIs to do this, and I haven't really dug deep into how searches work in Rolimons). Although, you might be able to find a third-party API that does support this.
